CREATE TABLE tbl_User (ID int primary key Identity(1,1),FIRST_NAME VARCHAR(200) NOT NULL,LAST_NAME VARCHAR(200),GENDER VARCHAR(50) NOT NULL,DOB DATE NOT NULL,EMAIL VARCHAR(500) NOT NULL,PASSWORD VARCHAR(200) NOT NULL);

CREATE TABLE tbl_LoginStatus (ID INT PRIMARY KEY IDENTITY(1,1),USER_ID INT NOT NULL,IS_ACTIVE BIT,LOGGED_IN DATETIME,LOGGED_OUT DATETIME
                              FOREIGN KEY (USER_ID) REFERENCES tbl_User(ID));


CREATE TABLE tbl_Tweet (ID INT PRIMARY KEY IDENTITY(1,1),TWEET VARCHAR(500) NOT NULL,USER_ID INT NOT NULL
                        FOREIGN KEY (USER_ID) REFERENCES tbl_User(ID));
